---
- name: Install mongo
  hosts: all
  become: true
  roles:
   - ../roles/db


#  tasks:
#  
#  - name: Add key
#    apt_key:       
#      id: EA312927
#      keyserver: keyserver.ubuntu.com
#
#  - name: Add repo
#    apt_repository: 
#       repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
#
#  - name: Install mongodb
#    apt:
#      name: mongodb-org
#      update_cache: yes
#
#  - name: Enable mongo
#    systemd:
#      name: mongod
#      enabled: yes
